### ISSUE TITLE
Sound - Weapon sounds

### ISSUE THREAD

**Issue by JonShard** [Arxcis/Sugarkick#12]
Making some stuff in audacity. Might not be optimal. Ill try.

**Comment by Arxcis** [comment]
Weapon pics for inspiration:

![Trompet-våpen](https://cloud.githubusercontent.com/assets/3092618/20220722/e3c33cf8-a82e-11e6-937a-04fd14a91c83.jpg)
![Dual-wield pistol](https://cloud.githubusercontent.com/assets/3092618/20220724/e5635566-a82e-11e6-9fd0-a94ac540d294.jpg)
![Team fortress 2 - minigun](https://cloud.githubusercontent.com/assets/3092618/20220725/e72e6eee-a82e-11e6-8ffd-72f30f45f34a.png)
![Cannon-gun/bazooka](https://cloud.githubusercontent.com/assets/3092618/20220726/e7aac9e4-a82e-11e6-8767-86b91d33bab5.png)

**Comment by Arxcis** [comment]
Weapon sounds are now fantastic! Amazing 👍
