### ISSUE TITLE
Hole

### ISSUE THREAD

**Issue by ghost** [Arxcis/Sugarkick#39]
require:
1. color different from map.
2. tag as "Hole"
3. prefab

**Comment by ghost** [comment]
A form with inconsistent edge would be preferable. This rules out sinle polygon sprite.
PolygonCollider2D seem good for detection.
GUI.DrawTextureWithTexCoords seem to only work with rectangles.
Sprite do not have a Color variable such as SpriteRenderer. 
An array with different holes might work but the updating the color in Start() did not show the sprite and sendt errors from seemingly unrelated file.
Renderer.SetPropertyBlock has a color value, but does not seem to be attatched to the sprite.

**Comment by Arxcis** [comment]
Holes have been implemented.
